### ISSUE TITLE
Robin Sojourner Wood Skins

### ISSUE THREAD

**Issue by Outworldz** [RuthAndRoth/Ruth#25] opened 2019-04-21 20:47 UTC
I received the official dump of Robin Sojourner Woods' skins today, licensed as CC-BY-SA-4.

Are we going to continue to add skins to the repo?  Open source skins are quite rare.  The TGA files may have a different copyright in text, however, she says the new license applies to all files in the dump.

https://www.dropbox.com/sh/aqq2ywtxkxk17jh/AAA_nNz5HXGiIUYP1oH75QW8a?dl=0

**Comment by aiaustin** [comment] 2019-04-21 20:59
I think its worth bringing things together where we have the permissions to do so.

Is there any limit or “cost” to doing so for us as RuthAndRoth on Github Fred?  

We might at some stage want to use a different repository outside of Ruth but under RuthAndRoth to bring related and addon things together and keep the core smaller.

**Comment by seriesumei** [comment] 2019-04-21 21:33
I think it would be a great idea to have a collection of open skins, but maybe in a dedicated repo?  I like the idea of a small set of skins included in the main repo but the rest can go into a new repo and we can have a different set of maintainers then too if we wanted to.

Austin, there is no cost for public things here, another organization that I help maintain on GitHub has >100 public repos (all Apache licensed) for no fee.

**Comment by aiaustin** [comment] 2019-04-22 07:59
Lets get that going shall we Serie and Fred? Skins are multi purpose and could be used beyond Ruth and Roth, so lets have one just for skins at first eh? We will insist on open source availability but be agnostic on the licence. We can have a Contrib/name convention again so its clear where the skins come from. Encourage a readme.txt for each contribution to give any credits and the licence type. 

Maybe Fred could put the Robin Wood skins in to establish this? Would you initiate the RuthAndRoth/Skins repository to do that Fred if you think its a good jdea.

Once established we could then move some of the skins over there, leaving just those core skins we intend to provide in the released HUDs, perhaps with uploaded UUIDs where we intend to use those in the new HUD scripts, and backed up there with IARs to let grids nit using the Hyorgrid pick them up and (usually) get the same UUIDs.

**Comment by aiaustin** [comment] 2019-04-22 08:15
I established RuthAndRoth/Skins to kick this off. Feel free to rearrange and edit things.

I did not add a specific license to the whole repository, as I assume we want individual creators to state their own license. If you feel some fall back license makes sense lets do that. If so I like CC-BY-SA.

It might be helpful to copy over the Licenses directory from RuthAndRoth/Ruth so we have the prototypical licenses we have used already within the repository?

**Comment by aiaustin** [comment] 2019-04-22 08:26
I need to make sure the admins and write access people are set up correctly Serie. Can you check that and set things appropriately?

**Comment by AdaRadius** [comment] 2019-04-22 10:16
Hi Fred, I started on Roth over the weekend, and started putting test skins together - merging elements of Eloh Eliot's early male skin lf0y, her skin improvements from the Starlight files, and LL character images for a little more texture.  When I get a little further along - Roth's UV maps need to be redone - I'll upload them to my contrib folder and you all can move them wherever you like, and/or post them at Outworldz.

**Comment by seriesumei** [comment] 2019-04-23 00:32
I am adding the RSW skins Fred posted above to the Skins repo, I will do it much like I did the Skins directory in the RuthAndRoth repo.  Thank you Fred for working this out with Robin!

How you y'all feel about duplicating things between the repos?  I do not want to do too much, but thought maybe duplicating the templates might be useful for someone who only wants to work with skins.

I am leaning toward organizing this by creator then skin name, assuming the names will identify male/female.  We can always add a M or F suffix if necessary I suppose.

I will push this up as a PR so we can look at it before committing large binary files to the repo in case we want to make major changes...

**Comment by seriesumei** [comment] 2019-04-23 02:41
I just pushed up https://github.com/RuthAndRoth/Skins/pull/1 to the Skins repo adding Robin's Sylvia.  I left the files as TGA as I did not see a big reason to convert them.  If we want to do anything different of that sort we should before merging that PR as it is rather large.

**Comment by aiaustin** [comment] 2019-04-23 07:30
My suggestion is that the things directly used to build, release or use Ruth and Roth should be directly in the Ruth repository.  So that would include the UV maps and any core templates. And I suggest any specific skins we include in the initial HUDs whether that is by texture or UUID reference. But we can and should I think include those duplicated in the Skins repository so that becomes a stand alone resource in its own right.

Se ought to decide if we are going to include the skins made for RC#1 through RC#3, i.e. Shin’s AGPL licensed HUD and its initial contents. Those skins are 512x512 and include his “dragon tattoo” variants.  What di you think about that Fred?

**Comment by aiaustin** [comment] 2019-04-23 07:33
I am not sure we should just rely on skin names to identify male and female. Why not encourage a clear separation under Contrib/Your Name/Female  and .../Male directories?

**Comment by seriesumei** [comment] 2019-04-24 00:54
OK, I will prepare the UV maps and templates for both repos, I think that makes sense and is not too large of a duplication.

About the Male/Female, I was on the fence about adding another directory layer, I like having things easy to find, but I think this would still be OK.  I do want to use basically the same rules for the Skins repo Contrib that we do in the Ruth repo, it is the workspace for contributors and as bits are finalized they be stored into the main directories.  I don't think we will have as much activity here so it might be sparse, that is OK.

Skins
|- Contrib
|. |- <creator name>
|. |- <creator name>
|- Female
|  |- <creator/skin name>
|  |- <creator/skin name>
|- Male
|  |- <creator/skin name>
|  |- <creator/skin name>

**Comment by aiaustin** [comment] 2019-04-24 07:34
I actually meant for Male and Female to be placed under the individual contributor folders Serie. So within the individual contributor folder They could place their readme, license details, etc at the top level and then their skins in some way clearly differentiated as Male or Female (or could be gender “Neutral” or Other?).

I think splitting individual contributions under a top level Male and Female folder would be awkward.

**Comment by seriesumei** [comment] 2019-04-24 11:40
OK, I can go either way.  I was thinking about someone browsing for a new skin, gender is usually the first filter applied.  But if you want to link through Elon Eliot's skins creator is the first filter.  I would be happy to have the problem of there being too many to just look through them all!

**Comment by aiaustin** [comment] 2019-04-26 07:49
I am changing my mind on this as it does make browsing harder with more directory levels.  Lets not be too prescriptive. Just put skins in suitable folders.  We might encourage the folder names to start with F- or M- if its unclear?

**Comment by seriesumei** [comment] 2019-04-26 11:18
I updated https://github.com/RuthAndRoth/Skins/pull/1 to use the F- prefix to set the example.  So that gives us:

Skins
|- Contrib
|. |- <creator>
|. |- <creator>
|- F-<creator/skin name>
|- F-<creator/skin name>
|- M-<creator/skin name>

**Comment by aiaustin** [comment] 2019-04-26 14:08
Go with what you feel is right Serie... but my comment was meant o suggest  clustering by exh creator so they have their own directory under Contrib exactly as we have for Ruth... so 

Skins
|- Contrib
|-|-  ...
|-|- creator name
|-|-|- Readme
|-|-|- License
|-|-|- F-skin name
|-|-|- F-skin name
|-|-|- M-skin name
|-|- creator name
...

**Comment by seriesumei** [comment] 2019-04-26 15:08
OK< I had assumed we would also have some 'curated' set of skins at the top level.  What if we take your approach and just leave off the Contrib?  What else were you thinking we would have at the top?

**Comment by aiaustin** [comment] 2019-04-26 17:07
I also had in mind that we might have some selected content at the top level relevant directly to RuthAndRoth releases or used in RuthAndRoth HUDs, etc.  So lets leave the Contrib idea in there for now shall we?  It keeps it in a similar style to the Ruth repository and we can always restructure..

**Comment by seriesumei** [comment] 2019-04-26 22:07
OK, sounds good!  I'verevised my PR, if you are fine with it you can merge https://github.com/RuthAndRoth/Skins/pull/1.

**Comment by aiaustin** [comment] 2019-04-27 08:05
I merged the first version of this now Serie. I assume you could have done the merge yourself and were just checking back with me? But please check you have full permissions on the Skins repository as intended or advise what needs to change.

Looking through the directories for the Sylvia skins I see some files that say their are “copy” of another with the same base file name. We need to check if that is the case and if so remove them I think. Check needed.

Also, some files have an ampersand in the file name. I think that could be seriously problematic in some environments. Shall we replace those P&P file name parts with PandP?

https://www.mtu.edu/umc/services/digital/writing/characters-avoid/

**Comment by seriesumei** [comment] 2019-04-27 15:21
I could have merged it, but since this was the beginning and we were still sorting it out I wanted to be sure we were on the same page first.

I did not notice the copies, I will look at that, it may be that some of the testing directories are duplicates and git figured that out.

And totally yes on renaming to limit the characters.  I even don't like spaces in filenames but have learned that is a futile effort for a lot of people that do not use command lines.

I think I will take another crack at this and do a force-push over this commit because we may be able to eliminate some of the files, and this repo is going to grow rather large since these are already compressed files.  So hold off adding anything else until then... :)

**Comment by aiaustin** [comment] 2019-04-27 16:43
Over to you Serie.

Also, there are some “Tests” and “Test Skins” sub directories. Check those out too and see if they ought to be deleted. If left in at lest lets rename them all the same way.

**Comment by seriesumei** [comment] 2019-04-27 23:58
OK, all pushed.  I force pushed so you'll have to overwrite your master branch.

I removed the test directories and fixed a bunch of filenames.   I think anything else to fix we'll just do normally now.  (I had a heck of a time getting the author and committer set properly on that...)

I am going to close this issue, anything else we can do a new issue in the Skins repo.

**Closed as completed by seriesumei** 2019-04-27 23:58 UTC

**Comment by aiaustin** [comment] 2019-04-28 08:47
When I tried to update via GitHub desktop it said there were two conflicts on Readme.md and Contrib/Readme.md.  I fixed those by putting back the two typo corrections I had made and the conflicts went away.

But as far as I can see we still have file names with P&P (ampersand) in them Serie.  maybe I have just not understood how I am meant to pull the updates from GitHub using GitHub desktop?

**Comment by aiaustin** [comment] 2019-05-06 19:45
We also now have a RuthAndRoth/Skins repository so as to separate open source skin contributions from the main Ruth/Roth repository.

https://github.com/RuthAndRoth/Skins
